trustPolicy: no-downgrade
shellEmulator: true
packages:
  - examples/**

catalogs:
  dev:
    "@luxass/eslint-config": 7.2.0
    "@luxass/utils": 2.7.3
    "@nuxt/kit": 4.3.1
    "@nuxt/schema": 4.3.1
    "@rspack/core": 1.7.6
    "@types/node": 22.18.12
    "@types/react": 19.2.14
    "@types/react-dom": 19.2.3
    esbuild: 0.27.3
    eslint: 10.0.1
    publint: 0.3.17
    rolldown: 1.0.0-rc.5
    rollup: 4.59.0
    tsdown: 0.20.3
    typescript: 5.9.3
    vite: 7.3.1
    vitest: 4.0.18
    vitest-testdirs: 4.4.2
    webpack: 5.105.2

  example:
    "@astrojs/check": 0.9.6
    "@nuxtjs/tailwindcss": 6.14.0
    "@rspack/cli": 1.7.6
    "@tailwindcss/vite": 4.2.0
    "@vitejs/plugin-react": 5.1.4
    "@vitejs/plugin-vue": 6.0.4
    astro: 5.17.3
    autoprefixer: 10.4.24
    next: 16.1.6
    nuxt: 4.3.1
    postcss: 8.5.6
    postcss-loader: 8.2.1
    react: 19.2.4
    react-dom: 19.2.4
    react-router-dom: 7.13.0
    shiki: 3.22.0
    tailwindcss: 4.2.0
    ts-node: 10.9.2
    unplugin-vue-router: 0.19.2
    vite-plugin-inspect: 11.3.3
    vite-plugin-vue-devtools: 8.0.6
    vue: 3.5.28
    vue-loader: 17.4.2
    vue-router: 5.0.3
    vue-tsc: 3.2.5

  prod:
    "@rollup/pluginutils": 5.3.0
    smol-toml: 1.6.0
    unplugin: 3.0.0

onlyBuiltDependencies:
  - esbuild
